### ISSUE TITLE
Remount failed and other directory for PackageParser

### ISSUE THREAD

**Issue by maumi** [moosd/Needle#5]
Hey,
first some questions.
I have a Samsung S5 (G900F) with Phoenix Rom (debloated, deoxed) and I use microG.
A stupid question: what is the benefit of spoofing signature for microg?
I can use unifiedNLP and Blankmarket without correct signature.
Should it be possible with my phone and rom to inject the signature spoofing?
Your script don't run through.
First stop is where it tries to remount system.
Done this by my own in shell. Pulled the framework.jar
But in my case the file "PackageParser.smali" is not in 
/framework.jar.out/smali/android/content/pm/
but in
/framework.jar.out/smali_classes2/android/content/pm/
At the end at building the apk I get an exception, but before I adress this I thought I ask if the things I'm doing are senseless.

**Comment by ale5000-git** [comment]
Could you please open an issue in my fork ( https://github.com/ale5000-git/Tingle ) and post the original unpatched framework.jar so I can try to fix the problem?

**Comment by souramoo** [comment]
The reason why you might want to spoof a signature is to allow apps that use features like google maps/other play services features to communicate with microG instead of google play services, allowing you to replace google maps with openstreetmaps, etc. Otherwise, the play services library embedded into these apps will reject the signature from microG and will fail to display maps, etc.

It should be possible to inject this yourself (indeed, I'd been doing it for quite a while before getting round to writing a script to do it) as long as you can find PackageParser.smali and the appropriate function. All you need to do is either change the path in the script from `framework.jar.out/smali/...` to `framework.jar.out/smali_classes2/...` or put in the method in `fillinsig.smali` in somewhere yourself with your favourite text editor and hook it yourself (see the script for how I force `generatePackageInfo` to call the function in `fillinsig.smali`

I will fix this in a commit shortly to actually find the location of PackageParser.smali

**Comment by ale5000-git** [comment]
Should be fixed by pull request #25
