### ISSUE TITLE
Not working with Windows

### ISSUE THREAD

**Issue by fritti** [moosd/Needle#6]
Hello,

after doing a clean install of Cyanogenmod 13 on my LG G2 (D802) smartphone, I wanted to patch the framework with needle to enable signature faking.

I used windows for that, installed everything which is needed before (ADB driver, device driver, Java, Python) but can't get this to work.

Could someone please help me out?

C:\Needle-master>patch.py
 **\* Selected device 064f036f92af0f5c
 **\* Device detected! proceeding...
 **\* Working dir: C:\Users\User\AppData\Local\Temp\tmpak9oiocg
 **\* Rooting adbd...
restarting adbd as root
remount succeeded
 **\* Pulling framework from device...
3823 KB/s (5963412 bytes in 1.523s)
 **\* Disassembling framework...
I: Using Apktool 2.0.2 on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
 **\* Done. Now this won't hurt a bit...
 **\* Injection successful. Reassembling smali...
I: Using Apktool 2.0.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
W: Could not find resources
I: Building apk file...
 **\* Putting things back like nothing ever happened...
Traceback (most recent call last):
  File "C:\Needle-master\patch.py", line 114, in <module>
    subprocess.call(["zip", "-r", "../../../framework.jar", "classes.dex"])
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 560, in call
    with Popen(_popenargs, *_kwargs) as p:
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 950, in **init**
    restore_signals, start_new_session)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system can't find the mentioned file

C:\Needle-master>

**Comment by marzzzello** [comment]
I just installed OmniRom 6.0.1 on my Nexus 4, which does not (yet) support signature spoofing. I think it is the same issue but I used Debian to run the needle-patch.

```
user@mmvm:~/Downloads/Needle$ python3 patch.py 
 *** Selected device 00775d4f4e8e38e6
 *** Device detected! proceeding...
 *** Working dir: /tmp/tmpjyt4wo4g
 *** Rooting adbd...
restarting adbd as root
remount succeeded
 *** Pulling framework from device...
4276 KB/s (5848624 bytes in 1.335s)
 *** Disassembling framework...
I: Using Apktool 2.0.2 on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
 *** Done. Now this won't hurt a bit...
 *** Injection successful. Reassembling smali...
I: Using Apktool 2.0.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
W: Could not find resources
I: Building apk file...
 *** Putting things back like nothing ever happened...
Traceback (most recent call last):
  File "patch.py", line 114, in <module>
    subprocess.call(["zip", "-r", "../../../framework.jar", "classes.dex"])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'zip'
user@mmvm:~/Downloads/Needle$ 
```

Edit: I just tested it with cm13 and there is the same problem

**Comment by wuffleton** [comment]
Working fine for me. Since I don't have access to my Linux box right now, I decided to take a crack at it on Windows. Since I use chocolatey for package management, I was able to get everything I needed with `choco install adb jdk zip python3`. After opening a new PS window to make sure my environment was re-read, running the python script as described worked without a hitch.  

Judging from those python exceptions, both of your problems are the same - the 'zip' command doesn't exist in your executable path: `FileNotFoundError: [Errno 2] No such file or directory: 'zip'`

The Debian user can solve this by running: `sudo apt-get update && sudo apt-get install zip` from a terminal. After that, they should be good to go provided everything else is set up correctly.

On Windows, it's slightly more tedious if you don't use something like choco to automate package management (since it'll nicely add everything you need to your path without any tinkering). 

1) First of all, you need to grab InfoZip's 'zip' utility:
- 32-bit: http://fossies.org/windows/misc/zip300xn.zip
- 64-bit: http://fossies.org/windows/misc/zip300xn-x64.zip

2) Unzip this to a location where you can easily find it, for instance `C:\zip`
3) Add this folder to your PATH as `;C:\zip`
- HowToGeek has a good tutorial on how to do this: http://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/

4) If you did this correctly, when you open a new command prompt, you should be able to type `zip` and see the command line usage of the zip utility. At this point, you can now re-run the python script as instructed. 

For Windows, you could probably also edit line 114 of the python script to point to the full path of zip.exe, but you'll probably have to escape the backslashes in the path in order for this to work.

**Comment by Diapolo** [comment]
I can confirm it IS working in Windows, with Python 3.5.1 (in PATH), Android SDK (in PATH) and the Zip utility from above (also in PATH). No need to edit any file supplied in this repo.

**Comment by souramoo** [comment]
Added a dependency check in commit 9f0dbf9 to alert people to the fact that they need java, adb and zip installed if they do not already have them installed and available on their `$PATH`/`%path%`.
